### ISSUE TITLE
We really don't want to use this library at the moment, pls stop, thanks. :)

### ISSUE THREAD

**Issue by wioniqle-q** [tolgaozuygur/plantcord#47]
We really don't want to use this library at the moment, pls stop, thanks. :)

_Originally posted by @tolgaozuygur in https://github.com/tolgaozuygur/plantcord/issues/46#issuecomment-1094943573_

Diger refactorlara bakıp yorumlar mısınız peki

**Comment by tolgaozuygur** [comment]
Şu anda sistemde major değişiklikler yapıyoruz, conflict hell olmasın diye sonra bakalım mı

**Comment by wioniqle-q** [comment]
Tamamdır teşekkür ederim hocam
